spring:
  thymeleaf:
    cache: false
  # mysql-config
#  datasource:
#    url: jdbc:mysql://localhost/demodb
#    username: root
#    password: qwer
#    driver-class-name: com.mysql.jdbc.Driver
#    initialize: false

